### ISSUE TITLE
File and directory naming convention

### ISSUE THREAD

**Issue by dannycolin** [OpenScienceMOOC/site#11]
We should use a naming convention for files' and directories' names.

**Reasons**

- Case sensitive vs. insensitive

  On Mac/Linux, Filename.md and filename.md aren't the same file but on Windows they
are. That means we could overwrite by error a file.

- SEO ranking
  
  mysite.com/site and mysite.com/Site are seen as the same page by the major search engine. They would flag those pages as duplicate content and it can impact on our SEO ranking.

- Unsafe and reserved characters in URL

  That one is really technical! Even me, I learned the real reason today :).

  > The space character is unsafe because significant spaces may disappear and insignificant spaces may be introduced when URLs are transcribed or typeset or subjected to the treatment of word-processing programs. -- from [IEFT RFC 1738 Standard](https://www.ietf.org/rfc/rfc1738.txt)

  There's a list of other unsafe and reserved characters. In the next section I'll propose an easy solution.

**Solution**

- No capital letters permitted;
- Use only alphanumerical characters;
- Every files should use an hyphen in place of whitespace.

  ```
  John Smith.md : john-smith.md
  A_Picture_of_Me.jpg : a-picture-of-me.jpg
  ```

  > Consider using punctuation in your URLs. The URL http://www.example.com/green-dress.html is much more useful to us than http://www.example.com/greendress.html. We recommend that you use hyphens (-) instead of underscores (_) in your URLs. -- from [Google Guideline for their crawler bot](https://support.google.com/webmasters/answer/76329?hl=en)

**Tasks**

- [ ] rename all files and folders
- [ ] rewrite any line of code that point to a file (e.g metadata between --- at the top of certain files)

If you find other tasks that need to be done, don't hesitate to comment on this issue. I'll update that post if needed.

**Comment by Protohedgehog** [comment]
This is so awesome, thanks @dannycolin! I started going through the _people folder and edited them. I used underscores though - is that okay? Can change to dashes if not. 

I think @Kevin-Mattheus-Moerman did a pretty awesome job of this from the beginning, so not much left to do. Just the images, I think, mostly.

**Comment by dannycolin** [comment]
@Protohedgehog both hyphens and underscore are acceptable characters in a URL.

Just keep in mind that Google bot views hyphens in URLs as word separators and it ignores underscore. That means `my_page.html` will be interpreted as `mypage.html`. It might be best to use hyphens in that case.
