### ISSUE TITLE
Update modules page to include new logos 

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/site#15]
This page https://opensciencemooc.github.io/site/modules/ could be updated to reflect the new logos designed by @hiiammike. @dannycolin any quick way to do this? The html looks a little complicated for me..

**Comment by dannycolin** [comment]
Yep. I'll work on that tomorrow because it's #FreeSoftwareFriday :).

**Comment by Protohedgehog** [comment]
Oh, sweet, I had no idea that was even a thing! I'm gonna be mostly out of it for the next 5 days or so, but will check in every now and then :)

**Comment by dannycolin** [comment]
I don't think it's a thing. Could be nice tho. It's just that Friday is my day off ;). Anyway, I've changed the logos but I'll rework on that page later to resolve some accessibility issues.
