### ISSUE TITLE
Transfer website URL

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [OpenScienceMOOC/site#21]
We want to get the github built website which is currently here:
https://opensciencemooc.github.io/site/
To take over this URL of the old website:
https://opensciencemooc.eu/ 

When I did the migration for my own websites (e.g. kevinmoerman.org) I had help from a friend, so I do not fully remember the steps. We used cloudflare in the past and I think we followed these instructions: 
* https://help.github.com/articles/using-a-custom-domain-with-github-pages/
* https://medium.freecodecamp.org/an-illustrated-guide-for-setting-up-your-website-using-github-cloudflare-5a7a11ca9465   

It involves creating a `CNAME` file (e.g. https://github.com/Kevin-Mattheus-Moerman/Kevin-Mattheus-Moerman.github.io/blob/master/CNAME) and to make some settings over at cloudflare. Next we'll have to have the correct URL names in our `_config.yml` file. However I do not remember the full details of the steps over at cloudflare (or a similar service). Can other people help make the transfer happen? @dannycolin can you assist here too?

**Comment by dannycolin** [comment]
@Kevin-Mattheus-Moerman Yes, I can but I'll need access to the domain name or I can walkthrough someone via Slack (@Protohedgehog?)

Btw, GitHub made it even easier. They now support HTTPS :tada: ! so we don't need to use/set an external service with Cloudflare.

**Comment by Protohedgehog** [comment]
@dannycolin @Kevin-Mattheus-Moerman Working on this right now! Will update as soon as I have more :)

**Comment by Protohedgehog** [comment]
@Kevin-Mattheus-Moerman working on doing this now through Switchpoint to GoDaddy. It hit a snag, but hopefully can be resolved in the next few days.

**Comment by Protohedgehog** [comment]
ALMOST DONE, besides a couple of bugs with the headers for a couple of the tabs https://opensciencemooc.eu/ @Kevin-Mattheus-Moerman

**Comment by dannycolin** [comment]
I think we can close that one. If someone find an other bug don't hesitate to reopen it.
