### ISSUE TITLE
Can/should we build a forum into the existing site?

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/site#22]
Question for folks: How would you like it if we were to build a forum into the existing site? (note, atm the domain is being transferred over and opensciencemooc.eu will become the main domain shortly-ish).

At the moment I'm wondering now how easy/difficult it would be to essentially just host everything through the main site as a one stop shop, but then also externally host it through other places too.. 

So one of the big things with MOOCs these days is encouraging peer to peer learning within a community space, rather than just a unidirectional learning flow. And part of that could be easily achieved by having a forum, where people could come in and ask/answer Qs about the MOOC, and general open science stuff.

So P2P have this, and the concept of learning circles could be overlaid with each module, in theory.. https://community.p2pu.org/

I had a chat with @dannycolin about this already, who mentioned we could use some software called Discourse and host it ourselves, using some clever tech things that I have no idea about.

Thoughts?

**Comment by alexmorley** [comment]
FWIW I think technically this is very do-able. Discourse is a neat almost out-of-the box solution. 

On the other hand if we go ahead with this we will need to set in place some solid procedures for moderation which can be tricky to get right.

**Comment by dannycolin** [comment]
> I had a chat with @dannycolin about this already, who mentioned we could use some software called Discourse and host it ourselves, using some clever tech things that I have no idea about.

Here's a couple of other technical things we need to consider if we want to host it ourselves : 

- We need some people who want to maintain the server(s).
- We need to decide if we also run our own mail server [1] (for the email notifications) or
  if we use a third-party provider (e.g Mailgun, Sendgrid). The second option is more pricey.
  If we choose the first option, we need to make sure we have the technical skills and the time
  for that. 

[1] There's an Open Source software that can reduce the maintenance. It's called Mail-in-a-Box

**Comment by Protohedgehog** [comment]
OK, great, thanks @alexmorley and @dannycolin.

So, for moderation, does Discourse allow people to 'apply' to be moderators or anything? What we could do is ask if people want to use the MOOC content as teachers, perhaps one of the things they can or have to do as part of that is become a forum mod? We can apply the same CoC for the MOOC to that too probably.

So, if it is possible for me to maintain the servers, I can do that. We have the info@opensciencemooc.eu address already (and I use TinyLetter for managing the lists), but I suspect this might not be enough for what you are talking about here? If there is an open source provider that can help with that, that would be cool.

**Comment by Protohedgehog** [comment]
Note that I think this can be closed now, as Eliademy has a discussion forum for each module, and we have the Slack group now too.
