### ISSUE TITLE
Rewrite resources page in Markdown

### ISSUE THREAD

**Issue by dannycolin** [OpenScienceMOOC/site#25]
The resources page is written in HTML and it's really hard to read and maintain. So it would be nice if we could have a Markdown version.

In addition, we could also move each module's resources in the module's page it is linking to.

**Comment by Protohedgehog** [comment]
Reckon it would be easy enough to convert the html to md just using pandoc? If so, I can do that.

And yes, that would be cool. Someone also pointed out to me a few days ago that the links in the module page to the resources are broken, so need to fix that too. A hangover from the old website again.

**Comment by dannycolin** [comment]
Ahah I didn't think about pandoc but yes that should do the trick. Maybe there will be some cleaning to do after pandoc-ing it tho.

**Comment by Protohedgehog** [comment]
OK, here it is for now. https://github.com/OpenScienceMOOC/site/blob/master/resources.md

I have a loooot of travel up ahead so can work on this then. Woo.

**Comment by Protohedgehog** [comment]
Also, I assume that to make this the active page some things will need to be edited in other files too, right?

**Comment by dannycolin** [comment]
Pandoc broke the YAML syntax at the top. It's fixed now ;)

**Comment by dannycolin** [comment]
@Protohedgehog can I close this issue? :)

**Comment by Protohedgehog** [comment]
Yessss!
