### ISSUE TITLE
List of press articles in 2016~2018

### ISSUE THREAD

**Issue by charles-plessy** [OpenScienceMOOC/site#28]
Hi !

For ~2 years I have been doing a press survey related to open science; however I think that I am not going to use it by myself.  I was wondering if you would find it useful ?

Open science in the press
=========================

 - _In dramatic statement, European leaders call for ‘immediate’ open access to
   all scientific papers by 2020._ Martin EnserinkMay. 27, 2016 , 2:30 PM
   [ScienceInsider](http://www.sciencemag.org/news/2016/05/dramatic-statement-european-leaders-call-immediate-open-access-all-scientific-papers)
   
 - _Survey Launch on Public Attitudes Toward Genomic Data Sharing._  Allison
   Proffitt, June 13, 2016, [Bio-IT World](http://www.bio-itworld.com/2016/6/13/survey-launch-public-attitudes-toward-genomic-data-sharing.aspx)
   ([Link to press release](https://genomicsandhealth.org/link-pressreleaseyourdnayoursay))
   
 - _Reproducibility: Archive computer code with raw data._  Joseph I. Hoffman
   16 June 2016, [correspondance to Nature]( http://www.nature.com/nature/journal/v534/n7607/full/534326d.html)
   
 - _The ups and downs of data sharing in science._ Nature editorial, 23 June 2016
   (http://www.nature.com/news/the-ups-and-downs-of-data-sharing-in-science-1.20124)
   
 - _A major first step towards a new way of publishing_. F1000 Research blog, Rebecca Lawrence, 6 July 2016
   (http://blog.f1000research.com/2016/07/06/a-major-first-step-towards-a-new-way-of-publishing/)
   
 - _Promoting research data sharing at Springer Nature_. BioMed Central blog,
Iain Hrynaszkiewicz, 5 Jul 2016 (http://blogs.biomedcentral.com/bmcblog/2016/07/05/promoting-research-data-sharing-springer-nature/)
   
 - _European Cloud Initiative to give Europe a global lead in the data-driven economy_
   Press release related to the European Open Science Cloud, opening up by default all scientific data,
   quantom technology and European high performance computing, data storage and network infrastructure
   (http://europa.eu/rapid/press-release_IP-16-1408_en.htm).  Brussels, 19 April 2016
   
 - _European Open Science Cloud_. Nature Genetics editorial, 27 July 2016
   (http://www.nature.com/ng/journal/v48/n8/full/ng.3642.html)
   
 - _Legal confusion threatens to slow data science_. Nature, Simon Oxenham
   03 August 2016 (http://www.nature.com/news/legal-confusion-threatens-to-slow-data-science-1.20359)
   
 - _ExAC project pins down rare gene variants_. Nature editorial, 17 August 2016
   (http://www.nature.com/news/exac-project-pins-down-rare-gene-variants-1.20425)
   
 - _Announcement: Where are the data?_. Nature editorial, 07 September 2016
   (http://www.nature.com/news/announcement-where-are-the-data-1.20541)
   
 - _Being open: our policy on source code_. Rafal T. Marszalek and Louisa Flintoft,
   Genome Biology editorial, [Genome Biology 2016 17:172](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1040-y)
   
 - _Public licenses and data: So what to do instead?_ Luis Villa,
   (<http://lu.is/blog/2016/09/26/public-licenses-and-data-so-what-to-do-instead/>)
   
 - _Democratic databases: science on GitHub._  Jeffrey Perkel
   (<http://www.nature.com/news/democratic-databases-science-on-github-1.20719>)
   
 - _Editorial expression of concern_  Jeremy Berg
   (<http://science.sciencemag.org/content/354/6317/1242.1>) -- Following data
   lost by computer theft.
   
 - _Enhancing reproducibility for computational methods_  Victoria Stodden _et al._,
   (<http://science.sciencemag.org/content/354/6317/1240.full>)
   
 - _Preparing for Preprints_  Bernd Pulverer,
   (<http://dx.doi.org/10.15252/embj.201670030>) -- Editorial in the EMBO
   journal supporting the use of preprints and announcing the _"[extension
   of its] scooping protection to the day of posting the preprint version of the
   manuscript".
   
 - _Where are the data?_ <https://doi.org/10.1038/nbt.3774> -- Editorial in
   Nature Biotechnology announcing a new [policy](http://go.nature.com/2bf4vqn)
   requiring statements on data availability in manuscripts published in
   Nature journals.
   
 - _Announcement: Transparency upgrade for Nature journals_ -- [Editorial in
   Nature](http://www.nature.com/news/announcement-transparency-upgrade-for-nature-journals-1.21627)
   (15 March 2017) announcing that nature jourals embrace the Transparency Openness
   Promotion (TOP) guidelines.
   
 - _New services to support open research_ -- [Article on BioMedCentral Blog]
   (http://blogs.biomedcentral.com/bmcblog/2017/04/27/new-services-to-support-open-research/)
   by Iain Hrynaszkiewicz (27 Apr 2017), announcing Springer Nature's new
   [data support services](http://www.springernature.com/de/group/data-policy/data-support-services).

 - _A nod to public open access infrastructures_ -- Benedikt Fecher, Sascha Friesike
   and Gert G. Wagner, correspondence in [Science 23 Jun 2017: Vol. 356, Issue 6344, pp. 1242](http://science.sciencemag.org/content/356/6344/1242),
   advocating the idea of an infrastructure on top of which scientific
   communities could easily run their own journals.
   
 - _Data models to GO-FAIR_ -- Editorial in
   [Nature Genetics, 28 June 2017](https://doi.org/doi:10.1038/ng.3910) calling
   for submission of supplemental data in RDF format (instead of Excel tables etc).
   At the moment, the estimated amount of work for the conversion is two days,
   with a dedicated data engineer.
   
 - _Google DeepMind 1.6m patient record deal 'inappropriate'_ -- Article in
   [The Guardian, Tuesday 16 May 2017 12.24 BST](https://www.theguardian.com/technology/2017/may/16/google-deepmind-16m-patient-record-deal-inappropriate-data-guardian-royal-free)
   (see also [RFA0627721](https://ico.org.uk/media/action-weve-taken/undertakings/2014352/royal-free-undertaking-03072017.pdf)).
   
 - _Open data: support from Swiss funder_ -- Matthias Egger & Angelika Kalt,
    Correspondence in [Nature, 547, 403 (27 July 2017)](https://doi.org/10.1038/547403b)
    -- Explainins the policy of the Swiss National Science Foundation (SNSF)
    to require "FAIR" data management and support it with 10,000 Swiss francs.
    
 - _Sharing images_ -- [Editorial in Nature Methods (14, 753
   (2017))](https://doi.org/10.1038/nmeth.4389) inviting readers to _"consider
   making their image data available and to communicate with [the journal] their
   views regarding the potential value or inconveniences of this practice."_
   
 - _Open data sharing and the Global South—Who benefits?_ -- Policy Forum in
    [Science  09 Feb 2018, Vol. 359, Issue 6376, pp. 642-643](https://doi.org/10.1126/science.aap8395)
    reminding that _"researchers using open data should strive to conduct
    ethical studies relevant to local communities and return results to them"_.
    
 - _Analytical Transparency and Reproducibility in Human Neuroimaging Studies_ --
   Editorial from Marina Picciotto in [The Journal of Neuroscience, 4 April 2018,
   38 (14) 3375-3376](https://doi.org/10.1523/JNEUROSCI.0424-18.2018),
   advocating the preregistration of experiment designs to prevent post-hoc
   rationalisation of research results.

**Comment by jcolomb** [comment]
Hi. Sounds great. I am not sure wjether we can use it in the mooc, but it would be worth looking for the integration of that data into oatp (peter suber project on surveying all open science news). I do not have the link at hand, but search for oatp tagteam and you should find it...

Am 7. November 2018 06:28:40 MEZ schrieb Charles Plessy <notifications@github.com>:
>Hi !>
>>
>For ~2 years I have been doing a press survey related to open science;
>however I think that I am not going to use it by myself.  I was
>wondering if you would find it useful ?>
>>
>>
>Open science in the press>
>=========================>
>>
>- _In dramatic statement, European leaders call for ‘immediate’ open
>access to>
>all scientific papers by 2020._ Martin EnserinkMay. 27, 2016 , 2:30 PM>
>[ScienceInsider](http://www.sciencemag.org/news/2016/05/dramatic-statement-european-leaders-call-immediate-open-access-all-scientific-papers)>
>   >
>- _Survey Launch on Public Attitudes Toward Genomic Data Sharing._ 
>Allison>
>Proffitt, June 13, 2016, [Bio-IT
>World](http://www.bio-itworld.com/2016/6/13/survey-launch-public-attitudes-toward-genomic-data-sharing.aspx)>
>([Link to press
>release](https://genomicsandhealth.org/link-pressreleaseyourdnayoursay))>
>   >
>- _Reproducibility: Archive computer code with raw data._  Joseph I.
>Hoffman>
>16 June 2016, [correspondance to Nature](
>http://www.nature.com/nature/journal/v534/n7607/full/534326d.html)>
>   >
>- _The ups and downs of data sharing in science._ Nature editorial, 23
>June 2016>
>(http://www.nature.com/news/the-ups-and-downs-of-data-sharing-in-science-1.20124)>
>   >
>- _A major first step towards a new way of publishing_. F1000 Research
>blog, Rebecca Lawrence, 6 July 2016>
>(http://blog.f1000research.com/2016/07/06/a-major-first-step-towards-a-new-way-of-publishing/)>
>   >
>- _Promoting research data sharing at Springer Nature_. BioMed Central
>blog,>
>Iain Hrynaszkiewicz, 5 Jul 2016
>(http://blogs.biomedcentral.com/bmcblog/2016/07/05/promoting-research-data-sharing-springer-nature/)>
>   >
>- _European Cloud Initiative to give Europe a global lead in the
>data-driven economy_>
>Press release related to the European Open Science Cloud, opening up by
>default all scientific data,>
>quantom technology and European high performance computing, data
>storage and network infrastructure>
>(http://europa.eu/rapid/press-release_IP-16-1408_en.htm).  Brussels, 19
>April 2016>
>   >
>- _European Open Science Cloud_. Nature Genetics editorial, 27 July
>2016>
>   (http://www.nature.com/ng/journal/v48/n8/full/ng.3642.html)>
>   >
>- _Legal confusion threatens to slow data science_. Nature, Simon
>Oxenham>
>03 August 2016
>(http://www.nature.com/news/legal-confusion-threatens-to-slow-data-science-1.20359)>
>   >
>- _ExAC project pins down rare gene variants_. Nature editorial, 17
>August 2016>
>(http://www.nature.com/news/exac-project-pins-down-rare-gene-variants-1.20425)>
>   >
>- _Announcement: Where are the data?_. Nature editorial, 07 September
>2016>
>  (http://www.nature.com/news/announcement-where-are-the-data-1.20541)>
>   >
>- _Being open: our policy on source code_. Rafal T. Marszalek and
>Louisa Flintoft,>
>Genome Biology editorial, [Genome Biology 2016
>17:172](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1040-y)>
>   >
> - _Public licenses and data: So what to do instead?_ Luis Villa,>
>(<http://lu.is/blog/2016/09/26/public-licenses-and-data-so-what-to-do-instead/>)>
>   >
> - _Democratic databases: science on GitHub._  Jeffrey Perkel>
>(<http://www.nature.com/news/democratic-databases-science-on-github-1.20719>)>
>   >
> - _Editorial expression of concern_  Jeremy Berg>
>(<http://science.sciencemag.org/content/354/6317/1242.1>) -- Following
>data>
>   lost by computer theft.>
>   >
>- _Enhancing reproducibility for computational methods_  Victoria
>Stodden _et al._,>
>   (<http://science.sciencemag.org/content/354/6317/1240.full>)>
>   >
> - _Preparing for Preprints_  Bernd Pulverer,>
>(<http://dx.doi.org/10.15252/embj.201670030>) -- Editorial in the EMBO>
>journal supporting the use of preprints and announcing the
>_"[extension>
>of its] scooping protection to the day of posting the preprint version
>of the>
>   manuscript".>
>   >
>- _Where are the data?_ <https://doi.org/10.1038/nbt.3774> -- Editorial
>in>
>Nature Biotechnology announcing a new
>[policy](http://go.nature.com/2bf4vqn)>
> requiring statements on data availability in manuscripts published in>
>   Nature journals.>
>   >
>- _Announcement: Transparency upgrade for Nature journals_ --
>[Editorial in>
>Nature](http://www.nature.com/news/announcement-transparency-upgrade-for-nature-journals-1.21627)>
>(15 March 2017) announcing that nature jourals embrace the Transparency
>Openness>
>   Promotion (TOP) guidelines.>
>   >
>- _New services to support open research_ -- [Article on BioMedCentral
>Blog]>
>(http://blogs.biomedcentral.com/bmcblog/2017/04/27/new-services-to-support-open-research/)>
>by Iain Hrynaszkiewicz (27 Apr 2017), announcing Springer Nature's new>
>[data support
>services](http://www.springernature.com/de/group/data-policy/data-support-services).>
>>
>- _A nod to public open access infrastructures_ -- Benedikt Fecher,
>Sascha Friesike>
>and Gert G. Wagner, correspondence in [Science 23 Jun 2017: Vol. 356,
>Issue 6344, pp.
>1242](http://science.sciencemag.org/content/356/6344/1242),>
>   advocating the idea of an infrastructure on top of which scientific>
>   communities could easily run their own journals.>
>   >
> - _Data models to GO-FAIR_ -- Editorial in>
>[Nature Genetics, 28 June 2017](https://doi.org/doi:10.1038/ng.3910)
>calling>
>for submission of supplemental data in RDF format (instead of Excel
>tables etc).>
>At the moment, the estimated amount of work for the conversion is two
>days,>
>   with a dedicated data engineer.>
>   >
>- _Google DeepMind 1.6m patient record deal 'inappropriate'_ -- Article
>in>
>[The Guardian, Tuesday 16 May 2017 12.24
>BST](https://www.theguardian.com/technology/2017/may/16/google-deepmind-16m-patient-record-deal-inappropriate-data-guardian-royal-free)>
>(see also
>[RFA0627721](https://ico.org.uk/media/action-weve-taken/undertakings/2014352/royal-free-undertaking-03072017.pdf)).>
>   >
>- _Open data: support from Swiss funder_ -- Matthias Egger & Angelika
>Kalt,>
>Correspondence in [Nature, 547, 403 (27 July
>2017)](https://doi.org/10.1038/547403b)>
>-- Explainins the policy of the Swiss National Science Foundation
>(SNSF)>
>to require "FAIR" data management and support it with 10,000 Swiss
>francs.>
>    >
> - _Sharing images_ -- [Editorial in Nature Methods (14, 753>
>(2017))](https://doi.org/10.1038/nmeth.4389) inviting readers to
>_"consider>
>making their image data available and to communicate with [the journal]
>their>
>views regarding the potential value or inconveniences of this
>practice."_>
>   >
>- _Open data sharing and the Global South—Who benefits?_ -- Policy
>Forum in>
>[Science  09 Feb 2018, Vol. 359, Issue 6376, pp.
>642-643](https://doi.org/10.1126/science.aap8395)>
> reminding that _"researchers using open data should strive to conduct>
>ethical studies relevant to local communities and return results to
>them"_.>
>    >
>- _Analytical Transparency and Reproducibility in Human Neuroimaging
>Studies_ -->
>Editorial from Marina Picciotto in [The Journal of Neuroscience, 4
>April 2018,>
>   38 (14) 3375-3376](https://doi.org/10.1523/JNEUROSCI.0424-18.2018),>
>advocating the preregistration of experiment designs to prevent
>post-hoc>
>   rationalisation of research results.>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenScienceMOOC/site/issues/28

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Protohedgehog** [comment]
Hi @charles-plessy, this is very impressive, thank you! I imagine that many of these could be integrated into the 'key elements' files that accompany each module for the MOOC for now, where there are collected lists of key related posts. Feel free to integrate them there as you see fit! (e.g., here https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/key_elements.md#posts)
