### ISSUE TITLE
Eliademy

### ISSUE THREAD

**Issue by johav** [OpenScienceMOOC/site#34]
the homeage https://opensciencemooc.eu/ needs an update and can we make Eliademy more visible? Like add their logo and a button to register for the courses that are already available?

**Comment by Protohedgehog** [comment]
I believe that @dannycolin and others are working on that right now :)

**Comment by dannycolin** [comment]
Oh yea, I've been busy and haven't had enough time to work on the redesign lately. :( Anyway, I could probably work on a quick fix for the button/register thingy. @johav Do you have anything else in mind.

By the way, here's a mockup of the future homepage https://www.dannycolin.com/mockup/osm/osm-homepage-3.png

**Comment by Protohedgehog** [comment]
No worries, @dannycolin! I still owe you a tonne of ice cream/coffee etc. anyway for this :)

**Comment by johav** [comment]
looks great! Let's make sure the course material get's a prominent position?/it's own tab/subpage / easy to find etc.
Just wanted to make sure to have this on the list of things to do ;) Can I assist with anything re redesign?

**Comment by dannycolin** [comment]
> looks great!

Thanks :)

> Let's make sure the course material get's a prominent position?/it's own tab/subpage / easy to find etc.

Yes, there's a link in the menu. Every courses (modules) will have its own page. The resources page in the old design will be replace by a resource section in each courses' page. 

> Can I assist with anything re redesign?

For the moment, I've only done the mockups (static images) with the help of @hiiammike. I've uploaded the screenshots for the home, blog and team pages [here](https://www.dannycolin.com/mockup/osm/). Of course, feedback is always appreciate :) 

The blog and team page could probably be reworked a bit. The *Get Involved* page will need some content like "How to join the production team" and "How to become a sponsor/partners".  

If anyone as some knowledge in HTML/CSS, that could be helpful to speed up the development. For the technical details, the new website will be based on : 

- [Jekyll](https://jekyllrb/com)
- [Foundation 6](https://foundation.zurb.com/)

**Comment by Protohedgehog** [comment]
This is great, thanks for the update, @dannycolin!

**Comment by dannycolin** [comment]
And the quick fix is done! :) There's a link to module 5 with a mention about eliademy at the top of the homepage.

**Comment by Protohedgehog** [comment]
Oh, that was speedy, thanks @dannycolin!!
