### ISSUE TITLE
link in readme not working

### ISSUE THREAD

**Issue by jcolomb** [OpenScienceMOOC/site#38]
10 min. GIT tutorial link not directing to a tutorial.

**Comment by Protohedgehog** [comment]
Seems fine to me, the URL just has changed? @Kevin-Mattheus-Moerman is this is still the right page?

**Comment by pcmasuzzo** [comment]
This looks fine to me, too. Though connection is not secure (has always been the case).

**Comment by jcolomb** [comment]
rephrasing: the link is redirected to a higher level page, not going to a tutorial

**Comment by jcolomb** [comment]
https://try.github.io/levels/1/challenges/1 
go to  https://try.github.io

**Comment by dannycolin** [comment]
Looks like Github removed the 10min tut.

**Comment by dannycolin** [comment]
I've removed the broken link. If someone find an other 10min-ish tutorial don't hesitate to add it to the README.md :).
