### ISSUE TITLE
New subsections in the People page

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/site#39]
As we've reshuffled a bit, we're gonna need to have a new subsection for the people page. Atm, we have the Steering Committee and development team. Can we add a new subsection for 'Advisors', and then I can reshuffle the people and add new profiles as needed?

**Comment by bmkramer** [comment]
Sounds good to me!

Op zo 31 mrt. 2019 om 12:38 schreef Jon Tennant <notifications@github.com>:

**Comment by dannycolin** [comment]
> Can we add a new subsection for 'Advisors', and then I can reshuffle the people and add new profiles as needed?

Sure. Would you prefer to have one page with a section for each team or one page per team?

**Comment by Protohedgehog** [comment]
I think one page with a section for each team/group would be best. Thanks, @dannycolin!

**Comment by dannycolin** [comment]
@Protohedgehog oh I forgot to ask. Is this issue for the v1.0 or you also want it for the actual website?

**Comment by Protohedgehog** [comment]
Sorry, @dannycolin, I don't fully understand. I think just for the new website, if possible.

**Comment by dannycolin** [comment]
@Protohedgehog On the v1.0 branch, you can now move people's profile to the team folder they belong to.

**Comment by Protohedgehog** [comment]
Silly Q - how do I edit that branch on my local machine without overwriting the current master branch here? If that makes sense..

**Comment by dannycolin** [comment]
```
git fetch origin v1.0:v1.0
get checkout v1.0
```

Change `origin` to `upstream` if you are on your fork.

**Comment by Protohedgehog** [comment]
Okie dokie, think I got it..
