### ISSUE TITLE
Add newsletter

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/site#4]
https://opensciencemooc.eu/contact-us/newsletter/

Embed code:

 <form style="border:1px solid #ccc;padding:3px;text-align:center;" action="https://tinyletter.com/OpenScienceMOOC" method="post" target="popupwindow" onsubmit="window.open('https://tinyletter.com/OpenScienceMOOC', 'popupwindow', 'scrollbars=yes,width=800,height=600');return true"><p><label for="tlemail">Enter your email address</label></p><p><input type="text" style="width:140px" name="email" id="tlemail" /></p><input type="hidden" value="1" name="embed"/><input type="submit" value="Subscribe" /><p><a href="https://tinyletter.com" target="_blank">powered by TinyLetter</a></p></form>

**Comment by Kevin-Mattheus-Moerman** [comment]
Cool. Should be fine. Do you think it just involves pasting this into [Contact.html](https://github.com/OpenScienceMOOC/site/blob/master/Contact.html)?: 

```html
<form style="border:1px solid #ccc;padding:3px;text-align:center;" action="https://tinyletter.com/OpenScienceMOOC" method="post" target="popupwindow" onsubmit="window.open('https://tinyletter.com/OpenScienceMOOC', 'popupwindow', 'scrollbars=yes,width=400,height=300');return true">
  <p><label for="tlemail">Enter your email address to sign up for our newlsetter. Thanks, TinyLetter!</label></p>
  <p><input style="width:140px" name="email" id="tlemail" type="text"></p>
  <p><input value="1" name="embed" type="hidden"><input value="Subscribe" type="submit"></p>
</form>
```
I can check this this evening.

**Comment by Protohedgehog** [comment]
It might do. Put it here as a reminder to test.

**Comment by Protohedgehog** [comment]
Worked like a charm :) https://opensciencemooc.github.io/site/Contact/
