### ISSUE TITLE
Add infra blog post to site

### ISSUE THREAD

**Issue by tosteiner** [OpenScienceMOOC/site#60]
@dannycolin soo, I was thinking... if I wanted to add the [infrastructure post](https://github.com/tosteiner/OSMOOC-site/blob/master/_posts/2019-09-03-teaching-os-open-infrastructure-needed.md) to the blog roll, how would this work? 

Just add the md-file to https://github.com/OpenScienceMOOC/site/tree/master/_posts , and that's it? And where can I put media files? 
Thanks in advance!

(just thinking aloud here: maybe we can also pull Lisa's post in as per #47 ? cc @Protohedgehog )

**Comment by dannycolin** [comment]
Create a new markdown file in `_posts` following this naming convention

`YYYY-MM-DD-your-post-title.md`

After that, add the following metadata at the top of your post:

```
---
title: "Your Post Title"
author: "Your Name"
date: "YYYY-MM-DD"
layout: post
categories: cat1 cat2
---
```

Now for the images, create a folder `posts` inside `/assets/img/` and put your images in it. You should now be able to link to your image in your markdown file like so:

`![Image description](/assets/img/posts/your-image.ext)`

Don't hesitation to ping me on Slack if something doesn't work ;)

**Comment by dannycolin** [comment]
Done (#61). :tada:
