### ISSUE TITLE
Kill the Documents page

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/site#9]
Here: https://opensciencemooc.github.io/site/Documents/ - not needed anymore.

Is this just a case of deleting the Documents.html file, or will that cause a bit of a mess? @Kevin-Mattheus-Moerman @dannycolin

**Comment by dannycolin** [comment]
It should be ok. I tested it locally and nothing breaks.

**Comment by Protohedgehog** [comment]
Sweet, thanks! Before I close this - how do you do a local test like that..? I typically use RStudio for editing stuff, if that helps..

**Comment by dannycolin** [comment]
Jekyll provides a way to run a local web server so you can see the modifications in real-time. The instructions can be found here : https://jekyllrb.com/docs/

So basically, what I've done is : 

- Open a terminal
- Move to the directory where the source code is with the `cd` command. 
- Execute the command `bundle exec Jekyll serve` in a terminal. If there's no errors you should see a message containing a URL to view the website in your browser. Normally it looks like http://localhost:4000. 
- Temporally move the Document.html file outside of the source code directory. You can use the command `mv` or your file manager.
- Open the URL Jekyll gives me and look if everything is OK.

Those instructions should work under Linux and Mac. I don't remember how to do it under Windows.
If you have other questions don't hesitate. ;)

**Comment by dannycolin** [comment]
Since you've pushed a commit that deleted the document.html, I think it's safe to close this issue :).

**Comment by Protohedgehog** [comment]
Yes, can be closed! I hit a snag with the testing though, and got the error:

Could not locate Gemfile or .bundle/ directory

So will keep working on that. Man, Linux is tough..

**Comment by dannycolin** [comment]
@Protohedgehog what's your distribution (Linux version)? 

Hmm There's a Gemfile in the root directory. Have you tried to execute the command `bundle install`. It might resolves your issue.

**Comment by Protohedgehog** [comment]
I'm using Debian, version 9.4 apparently. 

I tried running that, but getting a tonne of errors.  Will leave it for now.. :)

**Comment by dannycolin** [comment]
Cool. I'm also on Debian ;). 

Hmm that's strange. If Ruby and Jekyll are installed, it should have worked. If you decide to retry and need help, don't hesitate to ask ;)
